version: '3'
services:

  gds:
    image: jsilveira1409/gds:latest
    ports:
      - "127.0.0.1:5000:5000" # Expose GUI on port 5000
    networks:
      my_network:
        ipv4_address: 172.30.0.4

  fsw:
    image: jsilveira1409/fsw:latest
    depends_on:
      - gds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - payload:/app/payload
      - sharepoint:/app/sharepoint
    networks:
      my_network:
        ipv4_address: 172.30.0.5
    
    command: ["./Compose", "-a", "172.30.0.4", "-p", "50000"]

##############################################################
########################## Payloads ##########################
##############################################################

  payload-nano:
    image: nano:latest
    volumes:
      - payload:/app/data
      - sharepoint:/app/sharepoint
    networks:
      my_network:
        ipv4_address: 172.30.0.10
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"           
      

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.30.0.0/20

volumes:
  payload:  
  sharepoint:

x-special:
  "com.docker.compose.project": "clustergate"