FROM python:3.9-slim

WORKDIR /app

COPY ./interface-mkr.py /app/

COPY ./pdb_fun.py /app/

COPY ./user.json /app/

RUN pip install pyserial

RUN pip install requests

CMD ["python3","-u", "interface-mkr.py"]