# Use an official Ubuntu image as the base image
FROM python:3.8-slim


# Set the working directory inside the container
WORKDIR /app

RUN mkdir -p /app/images

RUN pip install opencv-python-headless matplotlib

# Copy the Python script to the container
COPY histogram.py /app/histogram.py

# Run the histogram script
CMD ["python3","-u" ,"histogram.py"]
