ARG VARIANT="22.04"
FROM ubuntu:${VARIANT} as base

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    python3-setuptools \
    python3-pip 

RUN pip install pyserial

COPY    ./payload-nano.py ./payload.py

CMD   python3 -u payload.py 