FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt /app/

RUN pip install -r requirements.txt
RUN pip install requests
COPY ./nano.py /app/
COPY ./user.json /app/
COPY ./pdb_fun.py /app/

CMD ["python3","-u", "nano.py"]