FROM python:3.9-slim

WORKDIR /app

RUN pip install requests        # needed for the pdb_fun.py

COPY ./pdb_fun.py /app/
COPY ./user.json /app/
COPY ./payload.py /app/


CMD ["python3","-u", "payload.py"]